hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.show_sql=true
hibernate.format_sql=false
hibernate.hbm2ddl.auto=create
hibernate.connection.url=jdbc:mysql://localhost:3306/myFirstDataBase?serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
hibernate.connection.username=root
hibernate.connection.password=password
hibernate.jdbc.time_zone=UTC
hibernate.connection.timezone=UTC
